# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copying dist files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "deploy_front/"
          rm: false
          strip_components: 1

      - name: move files to production folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /var/www/html/lga/*
            mv -f /home/ubuntu/deploy_front/* /var/www/html/lga
      # - name: ssh deploy
      #   uses: easingthemes/ssh-deploy@v2.1.4
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.KEY }}
      #     REMOTE_HOST: ${{ secrets.HOST }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     REMOTE_PORT: ${{ secrets.PORT }}
      #     EXCLUDE: "/var/www/html/cronomap/"
      #     SOURCE: "dist/"
      #     TARGET: "/var/www/html/cronomap/"
